wallet:
  private_key: '0x{hex}'
  keystore:
    path: '{path}'
    password: '{password}'
  chain: 'mothership'
9c:
  rpc: 'https://{9c-rpc-url}/graphql'
  explorer: 'https://{9c-rpc-url}/graphql/explorer'
local_contract_address:
  libplanet_portal: '0x{hex}'
  libplanet_bridge: '0x{hex}'
  libplanet_transaction_processor: '0x{hex}'
  transaction_parser: '0x{hex}'
  aura_summon_parser: '0x{hex}'
  claim_items_parser: '0x{hex}'
  combination_equipment_parser: '0x{hex}'
  daily_reward_parser: '0x{hex}'
  explore_adventure_boss_parser: '0x{hex}'
  grinding_parser: '0x{hex}'
  hack_and_slash_parser: '0x{hex}'
  hack_and_slash_sweep_parser: '0x{hex}'
  rapid_combination_parser: '0x{hex}'
  transfer_asset_parser: '0x{hex}'
