wallet:
  private_key: '0x{hex}'
  keystore:
    path: '{path}'
    password: '{password}'
  chain: 'mothership'
9c:
  rpc: 'https://{9c-rpc-url}/graphql'
  rpc_explorer: 'https://{9c-rpc-url}/graphql/explorer'
