wallet:
  private_key: '0x{hex}'
  keystore:
    path: '{path}'
    password: '{password}'
  chain: 'mothership'
9c:
  rpc: 'https://{9c-rpc-url}/graphql'
  explorer: 'https://{9c-rpc-url}/graphql/explorer'
local:
  explorer: 'https://{local-rpc-url}/graphql'

local_contract_address:
  libplanet_portal: '0x{hex}'
  libplanet_bridge: '0x{hex}'
  libplanet_output_oracle: '0x{hex}'
